/*
 * Copyright 2016 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models.view.questionnaire

object Universities {
  val seq = Seq(
    ("Aberdeen", "1"),
    ("Abertay Dundee", "2"),
    ("Aberystwyth", "3"),
    ("Anglia Ruskin University", "4"),
    ("Aston University", "5"),
    ("Bangor", "6"),
    ("Bath", "7"),
    ("Bath Spa University", "8"),
    ("Bedfordshire", "9"),
    ("Birkbeck College (University of London)", "10"),
    ("Birmingham", "11"),
    ("Birmingham City University", "12"),
    ("Birmingham, University College", "13"),
    ("Bishop Grosseteste University College Lincoln", "14"),
    ("Bolton", "15"),
    ("Bournemouth University", "16"),
    ("Bournemouth, Arts Institute at ", "17"),
    ("BPP University College of Professional Studies", "18"),
    ("Bradford", "19"),
    ("Brighton", "20"),
    ("Bristol", "21"),
    ("Brunel University", "22"),
    ("Buckinghamshire New University", "23"),
    ("Cambridge", "24"),
    ("Cancer Research, Institute of (University of London)", "25"),
    ("Canterbury Christ Church University", "26"),
    ("Cardiff", "27"),
    ("Cardiff Metropolitan", "28"),
    ("Central Lancashire", "29"),
    ("Central School of Speech and Drama (University of London)", "30"),
    ("Chester", "31"),
    ("Chichester", "32"),
    ("City University, London", "33"),
    ("Conservatoire for Dance and Drama", "34"),
    ("Courtauld Institute of Art (University of London)", "35"),
    ("Coventry University", "36"),
    ("Cranfield University", "37"),
    ("Creative Arts, University for the", "38"),
    ("Cumbria", "39"),
    ("De Montfort University", "40"),
    ("Derby", "41"),
    ("Dundee", "42"),
    ("Durham University", "43"),
    ("East Anglia", "44"),
    ("East London", "45"),
    ("Edge Hill University ", "46"),
    ("Edinburgh", "47"),
    ("Edinburgh College of Art", "48"),
    ("Education, Institute of (University of London)", "49"),
    ("Essex", "50"),
    ("Exeter", "51"),
    ("Falmouth, University College", "52"),
    ("Glamorgan", "53"),
    ("Glasgow", "54"),
    ("Glasgow Caledonian University", "55"),
    ("Glasgow School of Art", "56"),
    ("Gloucestershire", "57"),
    ("Glyndwr University", "58"),
    ("Goldsmiths College (University of London)", "59"),
    ("Greenwich", "60"),
    ("Guildhall School of Music & Drama", "61"),
    ("Harper Adams University College", "62"),
    ("Heriot-Watt University ", "63"),
    ("Hertfordshire", "64"),
    ("Heythrop College (University of London)", "65"),
    ("Huddersfield", "66"),
    ("Hull", "67"),
    ("Imperial College London", "68"),
    ("Keele University", "69"),
    ("Kent", "70"),
    ("King's College (University of London)", "71"),
    ("Kingston University", "72"),
    ("Lancaster University", "73"),
    ("Leeds", "74"),
    ("Leeds College of Music", "75"),
    ("Leeds Metropolitan University", "76"),
    ("Leeds Trinity & All Saints ", "77"),
    ("Leicester", "78"),
    ("Lincoln", "79"),
    ("Liverpool", "80"),
    ("Liverpool Hope University", "81"),
    ("Liverpool Institute for Performing Arts", "82"),
    ("Liverpool John Moores University", "83"),
    ("London Business School (University of London)", "84"),
    ("London Metropolitan University", "85"),
    ("London School of Economics and Political Science", "86"),
    ("London School of Hygiene and Tropical Medicine", "87"),
    ("London South Bank University", "88"),
    ("London, the Arts", "89"),
    ("London, University College (University of London)", "90"),
    ("Loughborough University", "91"),
    ("Manchester", "92"),
    ("Manchester Metropolitan University", "93"),
    ("Marjon (University College Plymouth St Mark & St John)", "94"),
    ("Middlesex University", "95"),
    ("Napier University", "96"),
    ("Newcastle University", "97"),
    ("Newman University College", "98"),
    ("Northampton", "99"),
    ("Northumbria University", "100"),
    ("Norwich University College of the Arts", "101"),
    ("Nottingham", "102"),
    ("Nottingham Trent University", "103"),
    ("Open University", "104"),
    ("Open University in Scotland", "105"),
    ("Open University in Wales", "106"),
    ("Others (UK) including Colleges and Institutions of Higher Education", "107"),
    ("Overseas", "108"),
    ("Oxford", "109"),
    ("Oxford Brookes University", "110"),
    ("Plymouth", "111"),
    ("Portsmouth", "112"),
    ("Queen Margaret University, Edinburgh ", "113"),
    ("Queen Mary (University of London)", "114"),
    ("Queen's University, Belfast", "115"),
    ("Ravensbourne College of Design and Communication", "116"),
    ("Reading", "117"),
    ("Robert Gordon University", "118"),
    ("Roehampton University", "119"),
    ("Rose Bruford College", "120"),
    ("Royal Academy of Music (University of London)", "121"),
    ("Royal Agricultural College", "122"),
    ("Royal College of Art", "123"),
    ("Royal College of Music", "124"),
    ("Royal Holloway (University of London)", "125"),
    ("Royal Northern College of Music", "126"),
    ("Royal Scottish Academy of Music & Drama", "127"),
    ("Royal Veterinary College (University of London)", "128"),
    ("Saint Andrews", "129"),
    ("Saint George's (University of London)", "130"),
    ("Saint Mary's University College", "131"),
    ("Salford", "132"),
    ("School of Advanced Study (University of London)", "133"),
    ("School of Oriental and African Studies (University of London)", "134"),
    ("School of Pharmacy (University of London)", "135"),
    ("Scottish Agricultural College ", "136"),
    ("Sheffield", "137"),
    ("Sheffield Hallam University", "138"),
    ("Southampton", "139"),
    ("Southampton Solent University", "140"),
    ("Staffordshire University", "141"),
    ("Stirling", "142"),
    ("Strathclyde", "143"),
    ("Suffolk, University Campus", "144"),
    ("Sunderland", "145"),
    ("Surrey", "146"),
    ("Sussex", "147"),
    ("Swansea", "148"),
    ("Swansea Metropolitan University", "149"),
    ("Teesside", "150"),
    ("Thames Valley University", "151"),
    ("Trinity College, Carmarthen", "152"),
    ("Trinity Laban Conservatoire of Music and Dance", "153"),
    ("UHI Millennium Institute ", "154"),
    ("Ulster", "155"),
    ("University of London External System (Distance Learning)", "156"),
    ("University of London Institute in Paris", "157"),
    ("University of London Marine Biological Station, Millport", "158"),
    ("Wales, Institute, Cardiff", "159"),
    ("Wales, Lampeter", "160"),
    ("Wales, Newport", "161"),
    ("Wales, Trinity Saint David", "162"),
    ("Warwick", "163"),
    ("West of England, Bristol", "164"),
    ("West of Scotland ", "165"),
    ("Westminster", "166"),
    ("Winchester", "167"),
    ("Wolverhampton", "168"),
    ("Worcester", "169"),
    ("Writtle College", "170"),
    ("York", "171"),
    ("York St John University", "172"),
    ("Not applicable as existing Civil Servant", "174")
  )
}
